### ISSUE TITLE
Handling file save or upload operations

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/sciline#29]
Sciline is based on requesting a specific output (type). When we save a file or upload a file, then this would naively be `None`, which would not work. We can work around this, e.g., by returning a status or success object from the provider, which the user can "request".

There may be nothing to do here (in code), but we should probably write a documentation page with a useful suggestion, since I imagine this may not be obvious to users.

**Comment by jl-wynen** [comment]
## Uploading

When uploading with Scitacean, it makes sense to return the uploaded dataset because the client returns a modified dataset to reflect the upload:
```python
def upload(ds: Dataset, client: Client) -> UploadedDataset:
    return UploadedDataset(client.upload_new_dataset_now(ds))
```

## Saving

However, when writing files, there is not really any meaningful return value. It is tempting to use something like
```python
FileWritten = NewType("FileWritten", None)

def write(data: Data, filename: Filename) -> FileWritten:
    data.save(filename)
```
But mypy doesn't like using `NewType` with `None`. It also doesn't like using it with `type(None)` or `types.NoneType`.

However, using something else requires a return statement, e.g.:
```python
class Token: ...
FileWritten = NewType("FileWritten", Token)

def write(data: Data, filename: Filename) -> FileWritten:
    data.save(filename)
    return FileWritten()
```

Maybe `Annotated` can help here (see also #36). I did not test this!
```python
FileWritten = Annotated(None, "FileWritten")

def write(data: Data, filename: Filename) -> FileWritten:
    data.save(filename)
```

Alternatively, a decorator could inject the dummy return statement:
```python
class Token: ...
FileWritten = NewType("FileWritten", Token)

@triggers_side_effect(FileWritten)
def write(data: Data, filename: Filename) -> None:
    data.save(filename)
```

For now, I am simply going to add something to the docs.
